### ISSUE TITLE
PlotData::GetData efficiency

### ISSUE THREAD

**Issue by JacekW235068** [JacekW235068/ChartLib#6]
Method calculates and returns a **copy** of all visible elements. This is not perfect since large amount of data is copied.

**Comment by foralost** [comment]
Maybe returning a unique_ptr or taking one for a argument and storing them there? (C instincts)

**Comment by foralost** [comment]
or a reference to list as an argument

**Comment by JacekW235068** [comment]
Nope, as visible points are calculated "on the run" and exist only inside this method reference types won't work.
My idea is: delete this method and replace it with solution like  [this](https://stackoverflow.com/questions/8164567/how-to-make-my-custom-type-to-work-with-range-based-for-loopsl). (leave overload returning a reference to all data as it is).

**Comment by JacekW235068** [comment]
One more thing. `PlotData` should be suitable for further development. At minimum it should be possible to implement class based on a function instead of fixed data set as `PlotDataFun`(name is WIP) will be next added feature. Basic Idea is that data classes for this library can be base for user classes working with chart objects.
